[".vim/pack/plugins/start/nerdtree"]
  type = "git-repo"
  url = "https://github.com/preservim/nerdtree.git"
  refreshPeriod = "168h"
[".vim/colors/onedark.vim"]
  type = "file"
  url = "https://raw.githubusercontent.com/joshdick/onedark.vim/main/colors/onedark.vim"
  refreshPeriod = "168h"
[".vim/autoload/onedark.vim"]
  type = "file"
  url = "https://raw.githubusercontent.com/joshdick/onedark.vim/main/autoload/onedark.vim"
  refreshPeriod = "168h"
[".vim/pack/plugins/opt/chezmoi.vim"]
  type = "git-repo"
  url = "https://github.com/alker0/chezmoi.vim"
  refreshPeriod = "168h"
[".vim/pack/plugins/opt/lightline.vim"]
  type = "git-repo"
  url = "https://github.com/itchyny/lightline.vim"
  refreshPeriod = "168h"
[".vim/pack/plugins/opt/vim-gitbranch.vim"]
  type = "git-repo"
  url = "https://github.com/itchyny/vim-gitbranch"
  refreshPeriod = "168h"
[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".config/zsh/plugins/zsh-syntax-highlighting"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".config/zsh/plugins/zsh-completions"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-completions/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".config/zsh/plugins/zsh-autosuggestions"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-autosuggestions/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".config/zsh/plugins/zsh-history-substring-search"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-history-substring-search/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".config/zsh/plugins/zsh_codex"]
    type = "archive"
    url = "https://github.com/luodian/zsh_codex/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".config/zsh/themes/powerlevel10k"]
    type = "archive"
    url = "https://github.com/romkatv/powerlevel10k/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
{{ if eq .chezmoi.os "linux" -}}
["AUR/rofi-greenclip"]
    type = "archive"
    url = "https://aur.archlinux.org/cgit/aur.git/snapshot/rofi-greenclip.tar.gz"
    refreshPeriod = "168h"
    stripComponents = 1
{{ end }}
{{ if eq .chezmoi.os "linux" -}}
["AUR/volta-bin"]
    type = "archive"
    url = "https://aur.archlinux.org/cgit/aur.git/snapshot/volta-bin.tar.gz"
    refreshPeriod = "168h"
    stripComponents = 1
{{ end }}
