typeset -U path

if [[ -z "$LANG" ]]; then
	export LANG='en_US.UTF-8'
fi

path=(
	$path
	"${ZDOTDIR:-$HOME}/go/bin"
	"${ZDOTDIR:-$HOME}/.bin"
	"${ZDOTDIR:-$HOME}/.local/bin"
	"${ZDOTDIR:-$HOME}/.yarn/bin"
	"${ZDOTDIR:-$HOME}/.cargo/bin"
	"${ZDOTDIR:-$HOME}/google-cloud-sdk/bin"
	"${ZDOTDIR:-$HOME}/.dotnet/tools"
)
