#!/bin/env bash

approve() {
    while true; do
        read -p "$1 " yn
        case $yn in
            [Yy]* ) return 0;;
            [Nn]* ) return 1;;
            * ) echo "Please answer yes or no.";;
        esac
    done
}

command_exists() {
  type "$1" &> /dev/null ;
  if [ $? -eq 1 ]; then
    if type "pacman" &> /dev/null ; then
      echo "$1 not found. Aborting. Run pacman -S $1" >&2;
    else
      echo "pacman is not found" >&2;
    fi
    exit 1;
  fi
}

if [ ! -f ~/.vim/autoload/plug.vim ] && approve "Enable Plug for vim?"; then
  command_exists "curl" && curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim && vim +PlugInstall +qall
fi
