#!/bin/sh

userresources=$HOME/.Xresources
nordresources=$HOME/.Xresources.nord
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# Non-reparenting window managers
export _JAVA_AWT_WM_NONREPARENTING=1

# merge in defaults and keymaps

if [ -f $sysresources ]; then

    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then

    xrdb -merge "$userresources"
fi

if [ -f "$nordresources" ]; then

    xrdb -merge "$nordresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

setxkbmap -option caps:escape
setxkbmap -option XF86WakeUp:ctrl

# xset s 120 60

feh --bg-fill --sort mtime ~/Pictures/Wallpapers/*.jpg &
# xss-lock -- i3lock-fancy -gpf Comic-Sans-MS -- scrot -z&
# xss-lock -- i3lock -t -i ~/lock-screen.png&
# xbindkeys
# dunst&
# slstatus&
# dwmblocks&
# volumeicon&
# gxkb&
# cbatticon&
pcmanfm -d&
unclutter -root -noevents&

# exec dwm
exec i3

# killall pcmanfm gxkb xss-lock volumeicon cbatticon slstatus dunst unclutter 
killall pcmanfm unclutter 
