#!/bin/bash

[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources

feh --bg-fill --sort mtime ~/Pictures/Wallpapers/*.jpg &

while true; do
	xsetroot -name "$( date +"%F %R" )"
	sleep 1m
done &

unclutter -root -noevents &
xwrits &
compton -b

exec dwm

killall xwrits unclutter
